name: 'Self Docker'
description: 'Build docker image from repo'
branding:
  icon: 'box'
  color: 'orange'
  
inputs:
  build-dir:
    description: 'Docker build dir, correspond to the one argument of the docker build command'
    required: true

  dockerfile-path:
    description: '(default: <build-dir>/Dockerfile) Path to the Dockerfile used for the build, correspond to the -f argument of the docker build command'
    required: false
    default: ''
  
  image-name:
    description: 'Image name, the built image will be named <image-name>:<image-tag>'
    required: true
  
  image-tag:
    description: 'Image tag the built image will be named <image-name>:<image-tag>'
    required: true

runs:
  using: 'node16'
  main: 'index.js'
