on: [push, pull_request]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # Do not forget to checkout your repository ...
        uses: actions/checkout@v3

      - name: Build self-contained
        uses: ./
        with:
          build-dir: ./tests/self-contained
          image-name: self
          image-tag: contained

      - name: Run self-contained
        run: docker run --rm self:contained echo ok

      - name: Build without dockerfile in build dir
        uses: ./
        with:
          build-dir: ./tests/without-dockerfile
          dockerfile-path: ./tests/ExternalDockerfile
          image-name: without
          image-tag: dockerfile

      - name: Run without-dockerfile
        run: docker run --rm without:dockerfile cat bravo.txt

      - name: Build with structure test validation
        uses: ./
        with:
          build-dir: ./tests/structure-test
          image-name: structure
          image-tag: test
          structure-test-file: ./tests/structure-test/test.yaml
  
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: ./
        with:
          build-dir: ./tests/windows
          image-name: win
          image-tag: test
      - name: Run windows container
        run: docker run --rm win:test echo ok

      - name: Build with structure test validation
        uses: ./
        with:
          build-dir: ./tests/structure-test
          dockerfile-path: ./tests/structure-test/Dockerfile.windows
          image-name: structure
          image-tag: test
          structure-test-file: ./tests/structure-test/test.yaml
          
           
